In [1]:
import numpy as np

In [3]:
patient_age = np.array([25, 30, 40, 22, 35, 50, 29, 60, 41, 28])
avrg_age = patient_age.mean()

In [4]:
avrg_age

36.0

In [5]:
chol_level = np.array([210, 180, 230, 250, 300, 220, 200, 190])
chol_level.max()

300

In [6]:
blood_pre = np.array([120, 130, 140, 135, 125, 110, 145, 120, 130, 140, 150, 135])
blood_pre.std()

11.055415967851333

In [7]:
temperatures = np.array([37.1, 36.5, 37.3, 36.8, 37.0, 38.0, 36.7, 37.2, 36.9, 37.5])
temperatures.mean()

37.1

In [8]:
weight = np.array([60, 72, 65, 58, 82, 75, 70, 68, 66, 80])
flipped_w = np.flip(weight)
flipped_w

array([80, 66, 68, 70, 75, 82, 58, 65, 72, 60])

In [10]:
p_data = np.array([[25, 70, 120],[30, 80, 130],[40, 85, 140]])
p_data

array([[ 25,  70, 120],
       [ 30,  80, 130],
       [ 40,  85, 140]])

In [11]:
p_data[1:2,2:]

array([[130]])

In [14]:
arr = np.array([[5.6, 7.1, 6.2, 5.8],
[5.3, 6.9, 7.0, 6.5],
[5.7, 6.5, 6.8, 6.0],
[5.4, 7.0, 6.5, 5.9]]
)

In [16]:
np.sum(arr,axis=1)

array([24.7, 25.7, 25. , 24.8])

In [17]:
pa=np.array([[80, 85, 90],
[95, 92, 88],
[85, 83, 82],
[100, 105, 110],
[75, 78, 80]])


In [19]:
pa[2:3,:].mean()

83.33333333333333

In [28]:
np.array([[22.1, 23.5],
[27.8, 28.0],
[21.2, 20.9]])*np.array([60, 70, 80]).reshape(-1,1)

array([[1326., 1410.],
       [1946., 1960.],
       [1696., 1672.]])

In [30]:
a=np.array([[37.0, 36.5, 37.1, 36.9, 37.0],
[36.8, 37.3, 37.0, 36.7, 37.2]])

In [31]:
np.max(a,axis=1)

array([37.1, 37.3])

In [7]:
import pandas as pd

In [8]:
data = {'Name': ['John', 'Jane', 'Tom', 'Alice'],
        'Age': [28, 34, 45, 52],
        'Blood Pressure': [120, 130, 140, 150],
        'Cholesterol': [200, 220, 240, 260]}
data

{'Name': ['John', 'Jane', 'Tom', 'Alice'],
 'Age': [28, 34, 45, 52],
 'Blood Pressure': [120, 130, 140, 150],
 'Cholesterol': [200, 220, 240, 260]}

In [9]:
ata=pd.DataFrame(data)
datad

Name  Age  Blood Pressure  Cholesterol
0   John   28             120          200
1   Jane   34             130          220
2    Tom   45             140          240
3  Alice   52             150          260

In [10]:
data[data['Cholesterol']>220]

Name  Age  Blood Pressure  Cholesterol
2    Tom   45             140          240
3  Alice   52             150          260

In [11]:
data

Name  Age  Blood Pressure  Cholesterol
0   John   28             120          200
1   Jane   34             130          220
2    Tom   45             140          240
3  Alice   52             150          260

In [16]:
data_bmi = {'Name': ['John', 'Jane', 'Tom', 'Alice'],
        'Age': [28, 34, 45, 52],
        'Blood Pressure': [120, 130, 140, 150],
        'Cholesterol': [200, 220, 240, 260],
         'Height': [7, 8, 5, 6],
          'Weight': [30, 50, 75,65]}

In [18]:
df_bmi = pd.DataFrame(data_bmi)

In [20]:
df_bmi['BMI'] = df_bmi['Weight'] / (df_bmi['Height'] ** 2)

In [21]:
print(df_bmi)

    Name  Age  Blood Pressure  Cholesterol  Height  Weight       BMI
0   John   28             120          200       7      30  0.612245
1   Jane   34             130          220       8      50  0.781250
2    Tom   45             140          240       5      75  3.000000
3  Alice   52             150          260       6      65  1.805556


In [1]:
patient_blood_test = ({'Test ID': [1, 2, 3, 4],
                       'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
                       'Result': [5.6, 6.1, 5.8, 6.3]})


In [5]:
import pandas as pd

In [23]:
blood_pressure=pd.Series([120, 130, 140, 135, 125])

In [35]:
blood_pressure.max()


140

In [36]:
blood_pressure.min()

120

In [37]:
chol_level = pd.Series([210, 180, 220, 250, 280, 230])

In [38]:
chol_level[chol_level>220]

3    250
4    280
5    230
dtype: int64

In [39]:
patient_age =  pd.Series([35, 40, 25, 30, 45, 50, 55, 60, 65, 70])

In [40]:
patient_age.median()

47.5

In [43]:
weight_measurement = pd.Series([35, 40, 25, 30, 45, 50, 55, 60, 65, 70])
weight_measurement +5

0    40
1    45
2    30
3    35
4    50
5    55
6    60
7    65
8    70
9    75
dtype: int64

In [44]:
temp = pd.Series([37.2, 36.8, 37.5, 38.0, 36.6, 37.1, 36.9, 37.3, 37.4, 37.0])

In [46]:
temp.mean()

37.17999999999999

## Data Frame 


In [4]:
patient_df=pd.DataFrame(patient_blood_test)
patient_df

Test ID Patient Name  Result
0        1         John     5.6
1        2         Jane     6.1
2        3          Tom     5.8
3        4        Alice     6.3

In [6]:
patient_df[patient_df['Result']>6.0]

Test ID Patient Name  Result
1        2         Jane     6.1
3        4        Alice     6.3

In [7]:
patient_df['Result']>6.0

0    False
1     True
2    False
3     True
Name: Result, dtype: bool

In [8]:
patient_data=  {'Name': ['John', 'Jane', 'Tom', 'Alice'],
        'Age': [28, 34, 45, 52],
        'Blood Pressure': [120, 130, 140, 150],
        'Cholesterol': [200, 220, 240, 260],
         'Height': [7, 8, 5, 6],
          'Weight': [30, 50, 75,65]}

In [10]:
patient_data=pd.DataFrame(patient_data)
patient_data

Name  Age  Blood Pressure  Cholesterol  Height  Weight
0   John   28             120          200       7      30
1   Jane   34             130          220       8      50
2    Tom   45             140          240       5      75
3  Alice   52             150          260       6      65

In [13]:
patient_data[['Age','Height','Weight']].mean()

Age       39.75
Height     6.50
Weight    55.00
dtype: float64

In [16]:
treatment_details = {'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
                     'Treatment Type': ['Surgery', 'Consultation', 'Surgery', 'Consultation'],
                     'Treatment Date': ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01']}
treatment_details

{'Patient Name': ['John', 'Jane', 'Tom', 'Alice'],
 'Treatment Type': ['Surgery', 'Consultation', 'Surgery', 'Consultation'],
 'Treatment Date': ['2022-01-01', '2022-02-01', '2022-03-01', '2022-04-01']}

In [17]:
treatment_df= pd.DataFrame(treatment_details)
treatment_df

Patient Name Treatment Type Treatment Date
0         John        Surgery     2022-01-01
1         Jane   Consultation     2022-02-01
2          Tom        Surgery     2022-03-01
3        Alice   Consultation     2022-04-01

In [20]:
treatment_df[treatment_df['Treatment Type']=='Surgery']

Patient Name Treatment Type Treatment Date
0         John        Surgery     2022-01-01
2          Tom        Surgery     2022-03-01

In [29]:
treatment_df.tail(-1)

Patient Name Treatment Type Treatment Date
1         Jane   Consultation     2022-02-01
2          Tom        Surgery     2022-03-01
3        Alice   Consultation     2022-04-01